package interpreter.tree;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import renderable.RenderableBlock;
import codeblocks.Block;
import codeblocks.BlockConnector;

/**
 * This class is responsible for parsing a program given by the workspace.
 * @author Brandon Oubre
 */
public class Parser {
	/*
	 * Default results for missing arguments.
	 */
	private static final StringResult DEFAULT_STRING_RESULT = () -> "";
	private static final BooleanResult DEFAULT_BOOLEAN_RESULT = () -> false;
	private static final NumberResult DEFAULT_NUMBER_RESULT = () -> 0;
	
	/*
	 * Error Handling
	 */
	private List<ParseError> errors;
	private List<ParseError> warnings;
	
	/*
	 * The top-level blocks for each page.
	 */
	private Iterable<RenderableBlock> setupTopBlocks = null;
	//private Iterable<RenderableBlock> runtimeTopBlocks = null;
	
	/*
	 * Global variable look-up table.
	 */
	Map<String, Result> lookupTable;
	
	/**
	 * Create a new parser.
	 * @param setupTopBlocks The top-level blocks from the setup page.
	 * @param runtimeTopBlocks The top-level blocks from the runtime page.
	 */
	public Parser(Iterable<RenderableBlock> setupTopBlocks, Iterable<RenderableBlock> runtimeTopBlocks) {
		this.setupTopBlocks = setupTopBlocks;
		//this.runtimeTopBlocks = runtimeTopBlocks;
		
		errors = new LinkedList<>();
		warnings = new LinkedList<>();
		lookupTable = new HashMap<>();
	}
	
	/**
	 * Raise a parse error.
	 * @param msg An appropriate error message.
	 */
	public void raiseError(Block b, String msg) {
		errors.add(new ParseError(b, msg));
	}
	
	/**
	 * Raise a parse warning.
	 * @param msg An appropriate warning message.
	 */
	public void raiseWarning(Block b, String msg) {
		warnings.add(new ParseError(b, msg));
	}
	
	/**
	 * @return The errors that arose during the parse.
	 */
	public List<ParseError> getErrors() {
		return errors;
	}
	
	/**
	 * @return The warnings that arose during the parse.
	 */
	public List<ParseError> getWarnings() {
		return warnings;
	}
	
	/**
	 * Retrieve the friendly name of a block
	 * @param b The block to query.
	 * @return The friendly name of the argument block.
	 */
	private static String getFriendlyName(Block b) {
		return b.getProperty("friendlyName");
	}
	
	/**
	 * Parse the given program.
	 * Errors and warnings will be raised to the console.
	 * @return <tt>null</tt> if the parse fails. Otherwise returns the {@link Program} (parse tree) generated by the parse.
	 */
	public Program parse() {
		Program program  = null;
		
		//Clear errors and warnings.
		errors.clear();
		warnings.clear();
		
		//Do we have a program to parse?
		if (setupTopBlocks == null) {
			raiseError(null, "No program to parse.");
			return null;
		}
		
		//Find the setup block.
		Block setupBlock = null;
		for (RenderableBlock rb : setupTopBlocks) {
			Block b = rb.getBlock();
			if (b.getGenusName().equals("setup")) {
				if (setupBlock == null) {
					setupBlock = b;
				} else {
					raiseError(b, "Duplicate setup blocks.");
					return null;
				}
			} else {
				raiseWarning(b, "Orphaned top-level blocks will not be executed.");
			}
		}
		
		if (setupBlock == null) {
			raiseWarning(null, "No setup block. Assuming no setup routine.");
		} else {
			program = new Program(parseSetup(setupBlock));
		}	
		
		return program;
	}
	
	/**
	 * Parse the setup  block.
	 * @param b The block to parse.
	 * @return The resulting parse tree node.
	 */
	private Setup parseSetup(Block b) {
		return new Setup(b, parseCommandList(b, 0));
	}
	
	/**
	 * Parse a command block.
	 * @param b The block to parse.
	 * @return The resulting parse tree node.
	 */
	private Command parseCommand(Block b) {
		switch (b.getGenusName()) {
		case "print":
			return new Print(b, parseStringArgument(b, 0));
		case "if":
			return new If(b, parseBooleanArgument(b, 0), parseCommandList(b, 1), null);
		case "ifelse":
			return new If(b, parseBooleanArgument(b, 0), parseCommandList(b, 1), parseCommandList(b, 2));
		case "setvar-num":
			return new SetVariable<NumberResult>(b, lookupTable, parseStringArgument(b, 0), parseNumericArgument(b, 1));
		case "setvar-string":
			return new SetVariable<StringResult>(b, lookupTable, parseStringArgument(b, 0), parseStringArgument(b, 1));
		case "setvar-bool":
			return new SetVariable<BooleanResult>(b, lookupTable, parseStringArgument(b, 0), parseBooleanArgument(b, 1));
		default:
			assert false : "Unrecognized block genus. (Should not occur.)";
		return null; //Code should not be reached.
		}
	}
	
	/**
	 * Parse a StringResult block.
	 * @param b The block to parse.
	 * @return The resulting parse tree node.
	 */
	private StringResult parseStringResult(Block b) {
		switch (b.getGenusName()) {
		case "string":
			return new StringConstant(b);
		case "var-string":
			return new StringVariable(b, lookupTable);
		case "string-append":
			return new StringConcat(b, parseStringArgument(b, 0), parseStringArgument(b, 1));
		case "num-to-string":
			return new NumToString(b, parseNumericArgument(b, 0));
		case "bool-to-string":
			return new BoolToString(b, parseBooleanArgument(b, 0));
		default:
			assert false : "Unrecognized block genus. (Should not occur.)";
		return null; //Code should not be reached.
		}
	}
	
	/**
	 * Parse a NumberResult block.
	 * @param b The block to parse.
	 * @return The resulting parse tree node.
	 */
	private NumberResult parseNumberResult(Block b) {
		switch (b.getGenusName()) {
		case "number":
			return new NumberConstant(b);
		case "var-number":
			return new NumberVariable(b, lookupTable);
		case "pi":
			return new NumberConstant(b, Math.PI);
		case "e":
			return new NumberConstant(b, Math.E);
		case "sum":
			return new Sum(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "difference":
			return new Difference(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "product":
			return new Product(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "quotient":
			return new Quotient(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "power":
			return new Power(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "min":
			return new Min(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "max":
			return new Max(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "remainder":
			return new Remainder(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "random":
			return new RandomInt(b, parseNumericArgument(b, 0));
		case "round":
			return new Round(b, parseNumericArgument(b, 0));
		case "int":
			return new Int(b, parseNumericArgument(b, 0));
		case "abs":
			return new AbsoluteValue(b, parseNumericArgument(b, 0));
		case "sqrt":
			return new SquareRoot(b, parseNumericArgument(b, 0));
		case "sin":
			return new Sine(b, parseNumericArgument(b, 0));
		case "cos":
			return new Cosine(b, parseNumericArgument(b, 0));
		case "tan":
			return new Tangent(b, parseNumericArgument(b, 0));
		case "asin":
			return new ArcSine(b, parseNumericArgument(b, 0));
		case "acos":
			return new ArcCosine(b, parseNumericArgument(b, 0));
		case "atan":
			return new ArcTangent(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "log":
			return new Logarithm(b, parseNumericArgument(b, 0));
		case "ln":
			return new NaturalLogarithm(b, parseNumericArgument(b, 0));
		default:
			assert false : "Unrecognized block genus. (Should not occur.)";
		return null; //Code should not be reached.
		}
	}
	
	/**
	 * Parse a NumberResult block.
	 * @param b The block to parse.
	 * @return The resulting parse tree node.
	 */
	private BooleanResult parseBooleanResult(Block b) { 
		switch (b.getGenusName()) {
		case "true": //Combined case intentional.
		case "false":
			return new BooleanConstant(b);
		case "var-bool":
			return new BooleanVariable(b, lookupTable);
		case "and":
			return new LogicAnd(b, parseBooleanArgument(b, 0), parseBooleanArgument(b, 1));
		case "or":
			return new LogicOr(b, parseBooleanArgument(b, 0), parseBooleanArgument(b, 1));
		case "not":
			return new LogicNot(b, parseBooleanArgument(b, 0));
		case "num-equals":
			return new NumericEquals(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "num-not-equals":
			return new NumericNotEquals(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "bool-equals":
			return new BooleanEquals(b, parseBooleanArgument(b, 0), parseBooleanArgument(b, 1));
		case "bool-not-equals":
			return new BooleanNotEquals(b, parseBooleanArgument(b, 0), parseBooleanArgument(b, 1));
		case "lessthan":
			return new LessThan(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "greaterthan":
			return new GreaterThan(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "lessthanorequalto":
			return new LessThanOrEqual(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		case "greaterthanorequalto":
			return new GreaterThanOrEqual(b, parseNumericArgument(b, 0), parseNumericArgument(b, 1));
		default:
			assert false : "Unrecognized block genus. (Should not occur.)";
		return null; //Code should not be reached.
		}
	}
	
	/**
	 * Parse a list of chained commands.
	 * @param head The parent block of the command chain.
	 * @param socketNum Which socket the command chain is located at.
	 * @return A list of the commands attached to the specified socket.
	 */
	private List<Command> parseCommandList(Block head, int socketNum) {
		assert socketNum >= 0 && socketNum <= head.getNumSockets(): "Invalid socket number: " + socketNum;
		List<Command> commands = new ArrayList<>();
		BlockConnector connector = head.getSocketAt(socketNum);
		
		if (connector.hasBlock()) {
			while (connector.hasBlock()) {
				Block block = Block.getBlock(connector.getBlockID());
				commands.add(parseCommand(block));
				connector = block.getAfterConnector();
			}
		} else {
			raiseWarning(head, getFriendlyName(head) + " is missing commands. Assuming no commands attached.");
		}	
		
		return commands;
	}
	
	/**
	 * Parse a numeric argument.
	 * @param b The original block.
	 * @param socketNum Which argument to parse.
	 * @return The parsed argument.
	 */
	private NumberResult parseNumericArgument(Block b, int socketNum) {
		assert socketNum >= 0 && socketNum <= b.getNumSockets(): "Invalid socket number: " + socketNum;
		BlockConnector socket = b.getSocketAt(socketNum);
		if (socket.hasBlock()) {
			return parseNumberResult(Block.getBlock(socket.getBlockID()));
		} else {
			raiseWarning(b, getFriendlyName(b) + " block missing argument. Assuming 0 as value.");
			return DEFAULT_NUMBER_RESULT;
		}
	}
	
	/**
	 * Parse a string argument.
	 * @param b The original block.
	 * @param socketNum Which argument to parse.
	 * @return The parsed argument.
	 */
	private StringResult parseStringArgument(Block b, int socketNum) {
		assert socketNum >= 0 && socketNum <= b.getNumSockets(): "Invalid socket number: " + socketNum;
		BlockConnector socket = b.getSocketAt(socketNum);
		if (socket.hasBlock()) {
			return parseStringResult(Block.getBlock(socket.getBlockID()));
		} else {
			raiseWarning(b, getFriendlyName(b) + " block missing argument. Assuming empty string as value.");
			return DEFAULT_STRING_RESULT;
		}
	}
	
	/**
	 * Parse a boolean argument.
	 * @param b The original block.
	 * @param socketNum Which argument to parse.
	 * @return The parsed argument.
	 */
	private BooleanResult parseBooleanArgument(Block b, int socketNum) {
		assert socketNum >= 0 && socketNum <= b.getNumSockets(): "Invalid socket number: " + socketNum;
		BlockConnector socket = b.getSocketAt(socketNum);
		if (socket.hasBlock()) {
			return parseBooleanResult(Block.getBlock(socket.getBlockID()));
		} else {
			raiseWarning(b, getFriendlyName(b) + " block missing argument. Assuming false as value.");
			return DEFAULT_BOOLEAN_RESULT;
		}
	}
}
